import React, { useState } from 'react';
import DashboardLayout from '../../components/DashboardLayout';
import { MOCK_ANALYSES } from '../../data/mockData';
import { USER_MENU } from './UserDashboard';
import './AnalysisHistory.css';

const AnalysisHistory = () => {
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');

  const filtered = MOCK_ANALYSES.filter(a => {
    const matchSearch = a.prediction.toLowerCase().includes(search.toLowerCase()) ||
                       a.id.toLowerCase().includes(search.toLowerCase()) ||
                       a.date.includes(search);
    const matchFilter = filterStatus === 'all' ||
                       (filterStatus === 'detected' && a.prediction.includes('Psoriasis Detected') && !a.prediction.includes('No')) ||
                       (filterStatus === 'clear' && a.prediction.includes('No'));
    return matchSearch && matchFilter;
  });

  const handleDownload = (analysis) => {
    const reportText = `
PSORIASIS AI — ANALYSIS REPORT
================================
Report ID: ${analysis.id}
Generated: ${new Date().toLocaleString()}

PREDICTION:    ${analysis.prediction}
CONFIDENCE:    ${analysis.confidence}%
STATUS:        ${analysis.status}
ANALYSIS TIME: ${analysis.analysisTime}
MODEL:         ${analysis.modelVersion}
DATE:          ${analysis.date}

DISCLAIMER:
This report is generated by an AI model and is NOT a medical diagnosis.
Please consult a licensed dermatologist for professional medical advice.
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `psoriasis-report-${analysis.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout menuItems={USER_MENU} title="Analysis History">
      <div className="ahist">
        {/* ── Header ── */}
        <div className="ahist__header">
          <div>
            <h2 className="ahist__title">Analysis History</h2>
            <p className="ahist__subtitle">View and manage all your past psoriasis analyses</p>
          </div>
        </div>

        {/* ── Filters ── */}
        <div className="ahist__filters">
          <div className="ahist__search">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
              <circle cx="11" cy="11" r="8" stroke="currentColor" strokeWidth="2"/>
              <path d="M21 21l-4.35-4.35" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
            </svg>
            <input
              type="text"
              placeholder="Search by ID, prediction, or date..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="ahist__search-input"
              id="ahist-search-input"
            />
          </div>

          <div className="ahist__filter-pills">
            {[
              { key: 'all', label: 'All' },
              { key: 'detected', label: 'Detected' },
              { key: 'clear', label: 'Clear' },
            ].map(f => (
              <button
                key={f.key}
                className={`ahist__pill ${filterStatus === f.key ? 'ahist__pill--active' : ''}`}
                onClick={() => setFilterStatus(f.key)}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>

        {/* ── Table ── */}
        <div className="ahist__table-card">
          <div className="ahist__table-wrap">
            <table className="ahist__table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Date</th>
                  <th>Prediction</th>
                  <th>Confidence</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filtered.length > 0 ? filtered.map(a => (
                  <tr key={a.id}>
                    <td className="ahist__td-id">{a.id}</td>
                    <td className="ahist__td-date">
                      {new Date(a.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </td>
                    <td>
                      <span className={`ahist__badge ${a.prediction.includes('No') ? 'ahist__badge--green' : 'ahist__badge--red'}`}>
                        {a.prediction.includes('No') ? '✓' : '⚠'} {a.prediction}
                      </span>
                    </td>
                    <td>
                      <div className="ahist__conf">
                        <div className="ahist__conf-bar">
                          <div
                            className={`ahist__conf-fill ${a.confidence >= 90 ? 'ahist__conf-fill--high' : a.confidence >= 70 ? 'ahist__conf-fill--mid' : 'ahist__conf-fill--low'}`}
                            style={{ width: `${a.confidence}%` }}
                          />
                        </div>
                        <span className="ahist__conf-pct">{a.confidence}%</span>
                      </div>
                    </td>
                    <td>
                      <span className="ahist__badge ahist__badge--blue">
                        {a.status}
                      </span>
                    </td>
                    <td>
                      <div className="ahist__actions">
                        <button
                          className="ahist__action-btn"
                          title="View Report"
                          onClick={() => alert(`Viewing report for ${a.id}`)}
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none">
                            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" stroke="currentColor" strokeWidth="2"/>
                            <circle cx="12" cy="12" r="3" stroke="currentColor" strokeWidth="2"/>
                          </svg>
                        </button>
                        <button
                          className="ahist__action-btn"
                          title="Download Report"
                          onClick={() => handleDownload(a)}
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none">
                            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                          </svg>
                        </button>
                      </div>
                    </td>
                  </tr>
                )) : (
                  <tr>
                    <td colSpan="6" className="ahist__empty">
                      No analyses found matching your search.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* ── Summary footer ── */}
        <div className="ahist__footer">
          <span>Showing {filtered.length} of {MOCK_ANALYSES.length} analyses</span>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default AnalysisHistory;
