import React, { useState, useEffect } from 'react';
import DashboardLayout from '../../components/DashboardLayout';
import { api } from '../../services/api';
import { USER_MENU } from './UserDashboard';
import './AnalysisHistory.css';

const parseFeedback = (feedback) => {
  if (!feedback) return { recommendation: 'No recommendation provided.', notes: 'None', nextSteps: 'None' };
  
  const lines = feedback.split('\n');
  let recommendation = '';
  let notes = '';
  let nextSteps = '';
  
  for (let line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('Recommendation:')) {
      recommendation = trimmed.substring('Recommendation:'.length).trim();
    } else if (trimmed.startsWith('Clinical Notes:')) {
      notes = trimmed.substring('Clinical Notes:'.length).trim();
    } else if (trimmed.startsWith('Next Steps:')) {
      nextSteps = trimmed.substring('Next Steps:'.length).trim();
    }
  }
  
  // Fallback if not in standard formatted string
  if (!recommendation && !notes && !nextSteps) {
    return {
      recommendation: feedback,
      notes: 'See recommendation details above.',
      nextSteps: 'N/A'
    };
  }
  
  return {
    recommendation: recommendation || 'None',
    notes: notes || 'None',
    nextSteps: nextSteps || 'None'
  };
};

const AnalysisHistory = () => {
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [analyses, setAnalyses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedAnalysis, setSelectedAnalysis] = useState(null);
  const [requestingReviewId, setRequestingReviewId] = useState(null);

  const fetchAnalyses = async () => {
    try {
      const data = await api.get('/analyses');
      setAnalyses(data);
    } catch (err) {
      console.error("Error fetching analysis history:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAnalyses();
  }, []);

  const handleRequestReview = async (analysisId) => {
    setRequestingReviewId(analysisId);
    try {
      await api.post(`/analyses/${analysisId}/request-review`);
      // Re-fetch analyses to update status locally
      await fetchAnalyses();
      // Update selectedAnalysis in state if open to show status change
      setSelectedAnalysis(prev => prev && prev.id === analysisId ? { ...prev, status: 'pending_review' } : prev);
    } catch (err) {
      console.error("Error requesting review:", err);
      alert("Failed to request doctor review. Please try again.");
    } finally {
      setRequestingReviewId(null);
    }
  };

  const handleDownload = (analysis) => {
    const confidencePct = Math.round(analysis.result_confidence * 100);
    const dateFormatted = new Date(analysis.created_at).toLocaleString();
    const reportText = `
PSORIASIS AI — ANALYSIS REPORT
================================
Report ID: #${analysis.id}
Generated: ${new Date().toLocaleString()}

PREDICTION:    ${analysis.result_label.toUpperCase()}
CONFIDENCE:    ${confidencePct}%
STATUS:        ${analysis.status.toUpperCase()}
DATE SUBMITTED: ${dateFormatted}
IMAGE URL:     ${analysis.image_url}

DISCLAIMER:
This report is generated by an AI model and is NOT a medical diagnosis.
Please consult a licensed dermatologist for professional medical advice.
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `psoriasis-report-${analysis.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const filtered = analyses.filter(a => {
    const label = a.result_label || '';
    const dateString = new Date(a.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    
    const matchSearch = label.toLowerCase().includes(search.toLowerCase()) ||
                       a.id.toString().includes(search.toLowerCase()) ||
                       dateString.toLowerCase().includes(search.toLowerCase());
                       
    const matchFilter = filterStatus === 'all' ||
                       (filterStatus === 'detected' && label.toLowerCase() === 'psoriasis') ||
                       (filterStatus === 'clear' && label.toLowerCase() === 'normal skin');
                       
    return matchSearch && matchFilter;
  });

  if (loading) {
    return (
      <DashboardLayout menuItems={USER_MENU} title="Analysis History">
        <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '200px', color: 'rgba(255,255,255,0.6)' }}>
          <div style={{ fontSize: '1.2rem' }}>Loading history...</div>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout menuItems={USER_MENU} title="Analysis History">
      <div className="ahist">
        {/* ── Header ── */}
        <div className="ahist__header">
          <div>
            <h2 className="ahist__title">Analysis History</h2>
            <p className="ahist__subtitle">View and manage all your past psoriasis analyses</p>
          </div>
        </div>

        {/* ── Filters ── */}
        <div className="ahist__filters">
          <div className="ahist__search">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
              <circle cx="11" cy="11" r="8" stroke="currentColor" strokeWidth="2"/>
              <path d="M21 21l-4.35-4.35" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/>
            </svg>
            <input
              type="text"
              placeholder="Search by ID, prediction, or date..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="ahist__search-input"
              id="ahist-search-input"
            />
          </div>

          <div className="ahist__filter-pills">
            {[
              { key: 'all', label: 'All' },
              { key: 'detected', label: 'Detected' },
              { key: 'clear', label: 'Clear' },
            ].map(f => (
              <button
                key={f.key}
                className={`ahist__pill ${filterStatus === f.key ? 'ahist__pill--active' : ''}`}
                onClick={() => setFilterStatus(f.key)}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>

        {/* ── Table ── */}
        <div className="ahist__table-card">
          <div className="ahist__table-wrap">
            <table className="ahist__table">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Date</th>
                  <th>Prediction</th>
                  <th>Confidence</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filtered.length > 0 ? filtered.map(a => {
                  const confidencePct = Math.round(a.result_confidence * 100);
                  const isHealthy = a.result_label.toLowerCase().includes('normal');
                  
                  return (
                    <tr key={a.id}>
                      <td className="ahist__td-id">#{a.id}</td>
                      <td className="ahist__td-date">
                        {new Date(a.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </td>
                      <td>
                        <span className={`ahist__badge ${isHealthy ? 'ahist__badge--green' : 'ahist__badge--red'}`} style={{ textTransform: 'capitalize' }}>
                          {isHealthy ? '✓' : '⚠'} {a.result_label}
                        </span>
                      </td>
                      <td>
                        <div className="ahist__conf">
                          <div className="ahist__conf-bar">
                            <div
                              className={`ahist__conf-fill ${confidencePct >= 90 ? 'ahist__conf-fill--high' : confidencePct >= 70 ? 'ahist__conf-fill--mid' : 'ahist__conf-fill--low'}`}
                              style={{ width: `${confidencePct}%` }}
                            />
                          </div>
                          <span className="ahist__conf-pct">{confidencePct}%</span>
                        </div>
                      </td>
                      <td>
                        <span className={`ahist__badge ${a.status === 'reviewed' ? 'ahist__badge--green' : a.status === 'pending_review' ? 'ahist__badge--blue' : 'ahist__badge--blue'}`} style={{ opacity: a.status === 'pending_review' ? 0.8 : 1 }}>
                          {a.status === 'reviewed' ? 'Reviewed' : a.status === 'pending_review' ? 'Pending Review' : 'Completed'}
                        </span>
                      </td>
                      <td>
                        <div className="ahist__actions">
                          <button
                            className="ahist__action-btn"
                            title="View Report"
                            onClick={() => setSelectedAnalysis(a)}
                            id={`view-report-${a.id}`}
                          >
                            <svg width="15" height="15" viewBox="0 0 24 24" fill="none">
                              <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z" stroke="currentColor" strokeWidth="2"/>
                              <circle cx="12" cy="12" r="3" stroke="currentColor" strokeWidth="2"/>
                            </svg>
                          </button>
                          <button
                            className="ahist__action-btn"
                            title="Download Report"
                            onClick={() => handleDownload(a)}
                            id={`download-report-${a.id}`}
                          >
                            <svg width="15" height="15" viewBox="0 0 24 24" fill="none">
                              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                            </svg>
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                }) : (
                  <tr>
                    <td colSpan="6" className="ahist__empty">
                      No analyses found.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* ── Summary footer ── */}
        <div className="ahist__footer">
          <span>Showing {filtered.length} of {analyses.length} analyses</span>
        </div>
      </div>

      {/* ── Report Modal ── */}
      {selectedAnalysis && (
        <div className="ahist-modal" onClick={() => setSelectedAnalysis(null)} id="report-modal">
          <div className="ahist-modal__content" onClick={e => e.stopPropagation()}>
            <button className="ahist-modal__close" onClick={() => setSelectedAnalysis(null)} aria-label="Close modal">✕</button>
            
            <div className="ahist-modal__header">
              <h3 className="ahist-modal__title">Analysis Report Details</h3>
              <p className="ahist-modal__subtitle">Complete analysis profile and clinical reviews</p>
            </div>
            
            <div className="ahist-modal__grid">
              <div className="ahist-modal__img-container">
                <img src={selectedAnalysis.image_url} alt="Skin condition scan" className="ahist-modal__img" />
              </div>
              <div className="ahist-modal__details">
                <div className="ahist-modal__item">
                  <span className="ahist-modal__label">Analysis ID</span>
                  <span className="ahist-modal__value ahist-modal__value--id">#{selectedAnalysis.id}</span>
                </div>
                <div className="ahist-modal__item">
                  <span className="ahist-modal__label">Scanned Date</span>
                  <span className="ahist-modal__value">
                    {new Date(selectedAnalysis.created_at).toLocaleString('en-US', { month: 'long', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
                <div className="ahist-modal__item">
                  <span className="ahist-modal__label">Prediction result</span>
                  <span className="ahist-modal__value">
                    <span className={`ahist__badge ${selectedAnalysis.result_label.toLowerCase().includes('normal') ? 'ahist__badge--green' : 'ahist__badge--red'}`} style={{ textTransform: 'capitalize' }}>
                      {selectedAnalysis.result_label.toLowerCase().includes('normal') ? '✓' : '⚠'} {selectedAnalysis.result_label}
                    </span>
                  </span>
                </div>
                <div className="ahist-modal__item">
                  <span className="ahist-modal__label">Confidence Score</span>
                  <span className="ahist-modal__value" style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <div className="ahist__conf-bar" style={{ width: '120px' }}>
                      <div
                        className={`ahist__conf-fill ${selectedAnalysis.result_confidence >= 0.9 ? 'ahist__conf-fill--high' : selectedAnalysis.result_confidence >= 0.7 ? 'ahist__conf-fill--mid' : 'ahist__conf-fill--low'}`}
                        style={{ width: `${Math.round(selectedAnalysis.result_confidence * 100)}%` }}
                      />
                    </div>
                    <strong>{Math.round(selectedAnalysis.result_confidence * 100)}%</strong>
                  </span>
                </div>
              </div>
            </div>

            {/* Doctor Reviews section */}
            {selectedAnalysis.status === 'reviewed' && selectedAnalysis.reviews && selectedAnalysis.reviews.length > 0 ? (
              <div className="ahist-modal__reviews">
                <h4 className="ahist-modal__reviews-title">
                  👨‍⚕️ Doctor Consultation Review
                </h4>
                <div className="ahist-modal__review-item">
                  <div className="ahist-modal__review-field">
                    <span className="ahist-modal__review-label">Reviewing Doctor</span>
                    <span className="ahist-modal__value">
                      {selectedAnalysis.reviews[0].doctor?.full_name || 'Dermatologist'} 
                      {selectedAnalysis.reviews[0].doctor?.hospital ? ` (${selectedAnalysis.reviews[0].doctor.hospital})` : ''}
                    </span>
                  </div>
                  
                  {(() => {
                    const parsed = parseFeedback(selectedAnalysis.reviews[0].feedback);
                    return (
                      <>
                        <div className="ahist-modal__review-field">
                          <span className="ahist-modal__review-label">Clinical Notes</span>
                          <p className="ahist-modal__review-text">{parsed.notes}</p>
                        </div>
                        <div className="ahist-modal__review-field">
                          <span className="ahist-modal__review-label">Recommendations</span>
                          <p className="ahist-modal__review-text">{parsed.recommendation}</p>
                        </div>
                        <div className="ahist-modal__review-field">
                          <span className="ahist-modal__review-label">Suggested Next Steps</span>
                          <p className="ahist-modal__review-text">{parsed.nextSteps}</p>
                        </div>
                      </>
                    );
                  })()}
                </div>
              </div>
            ) : selectedAnalysis.status === 'pending_review' ? (
              <div className="ahist-modal__reviews" style={{ borderStyle: 'dashed', textAlign: 'center', padding: '20px' }}>
                <span style={{ fontSize: '1.5rem', display: 'block', marginBottom: '8px' }}>⏳</span>
                <span className="ahist-modal__review-label" style={{ color: '#EAB308' }}>Pending Dermatologist Review</span>
                <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.6)', marginTop: '6px' }}>
                  A clinical dermatologist is currently reviewing your scan results. We will update this report as soon as their feedback is submitted.
                </p>
              </div>
            ) : (
              <div className="ahist-modal__reviews" style={{ borderStyle: 'dashed', textAlign: 'center', padding: '20px' }}>
                <span style={{ fontSize: '1.5rem', display: 'block', marginBottom: '8px' }}>🔬</span>
                <span className="ahist-modal__review-label" style={{ color: '#63B3ED' }}>Clinical Review Available</span>
                <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.6)', marginTop: '6px', marginBottom: '14px' }}>
                  You can request a professional verification of your AI prediction from our affiliated dermatologists.
                </p>
                <button
                  className={`ahist-modal__req-btn ${requestingReviewId ? 'ahist-modal__req-btn--loading' : ''}`}
                  disabled={!!requestingReviewId}
                  onClick={() => handleRequestReview(selectedAnalysis.id)}
                  id="request-review-btn"
                >
                  {requestingReviewId ? 'Sending Request...' : '✉ Request Doctor Review'}
                </button>
              </div>
            )}

            <div className="ahist-modal__footer">
              <button className="ahist-modal__btn ahist-modal__btn--secondary" onClick={() => setSelectedAnalysis(null)}>Close</button>
              <button className="ahist-modal__btn ahist-modal__btn--primary" onClick={() => handleDownload(selectedAnalysis)}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
                Download Report
              </button>
            </div>
          </div>
        </div>
      )}
    </DashboardLayout>
  );
};

export default AnalysisHistory;
